enum EActionTypes {
  SET_INITIAL_ARRAY = 'APP@SET_INITIAL_ARRAY',
  SET_ARRAY = 'APP@SET_ARRAY',
  SET_SORTING_TICK_INTERVAL = 'APP@SET_SORTING_TICK_INTERVAL',
  SET_ARRAY_SORTING_IN_PROGRESS = 'APP@SET_ARRAY_SORTING_IN_PROGRESS',
  SET_ARRAY_SORTING_COMPLETED = 'APP@SET_ARRAY_SORTING_COMPLETED',
}

export default EActionTypes;
